DROP TABLE IF EXISTS artists;
CREATE TABLE IF NOT EXISTS artists (
   id INTEGER NOT NULL
    CONSTRAINT artists_pk PRIMARY KEY AUTOINCREMENT,
   name TEXT NOT NULL
);

DROP TABLE IF EXISTS labels;
CREATE TABLE IF NOT EXISTS labels (
   id INTEGER NOT NULL
    CONSTRAINT label_pk PRIMARY KEY AUTOINCREMENT,
   name TEXT NOT NULL
);

DROP TABLE IF EXISTS albums;
CREATE TABLE IF NOT EXISTS albums (
   id INTEGER NOT NULL
    CONSTRAINT album_pk PRIMARY KEY AUTOINCREMENT,
   artistid INTEGER NOT NULL,
   labelid INTEGER NOT NULL,
   name TEXT NOT NULL,
   released INTEGER DEFAULT NULL,
   FOREIGN KEY(artistid) REFERENCES artist(artistid),
   FOREIGN KEY(labelid) REFERENCES label(labelid)
);

DROP TABLE IF EXISTS charts;
CREATE TABLE IF NOT EXISTS charts (
   id INTEGER NOT NULL 
    CONSTRAINT simple_charts_pk PRIMARY KEY AUTOINCREMENT,
   albumid INTEGER NOT NULL,
   date INTEGER NOT NULL, 
   rank INTEGER NOT NULL,
   type INTEGER NOT NULL DEFAULT 0,
   FOREIGN KEY(albumid) REFERENCES albums(albumid)
);

DROP TABLE IF EXISTS simple_charts;
CREATE TABLE IF NOT EXISTS simple_charts (
   id INTEGER NOT NULL 
    CONSTRAINT simple_charts_pk PRIMARY KEY AUTOINCREMENT,
   artist TEXT NOT NULL,
   label TEXT,
   album TEXT,
   date INTEGER NOT NULL, 
   rank INTEGER NOT NULL,
   type INTEGER NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS shows;
CREATE TABLE IF NOT EXISTS shows (
   id INTEGER NOT NULL 
    CONSTRAINT shows_pk PRIMARY KEY AUTOINCREMENT,
   name TEXT NOT NULL,
   description TEXT DEFAULT NULL,
   genre TEXT DEFAULT NULL,
   type INTEGER NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS djs;
CREATE TABLE IF NOT EXISTS djs (
   id INTEGER NOT NULL 
    CONSTRAINT djs_pk PRIMARY KEY AUTOINCREMENT,
   dj_name TEXT DEFAULT NULL,
   real_name TEXT DEFAULT NULL,
   type INTEGER NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS spots;
CREATE TABLE IF NOT EXISTS spots (
   id INTEGER NOT NULL
    CONSTRAINT schedule_pk PRIMARY KEY AUTOINCREMENT,
   show_id INTEGER NOT NULL,
   day INTEGER NOT NULL,
   time INTEGER NOT NULL,
   FOREIGN KEY(show_id) REFERENCES shows(showid),
   UNIQUE(day, time)
);
